//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Şirket İsmi")]
        public string sirketAdi {
            get {
                return ((string)(this["sirketAdi"]));
            }
            set {
                this["sirketAdi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adres Satırı 1")]
        public string adres1 {
            get {
                return ((string)(this["adres1"]));
            }
            set {
                this["adres1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adres Satırı 2 ")]
        public string adres2 {
            get {
                return ((string)(this["adres2"]));
            }
            set {
                this["adres2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adres Satırı 3 ")]
        public string adres3 {
            get {
                return ((string)(this["adres3"]));
            }
            set {
                this["adres3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0354 354 54 54")]
        public string telefon {
            get {
                return ((string)(this["telefon"]));
            }
            set {
                this["telefon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vergiDairesi {
            get {
                return ((string)(this["vergiDairesi"]));
            }
            set {
                this["vergiDairesi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vergiNo {
            get {
                return ((string)(this["vergiNo"]));
            }
            set {
                this["vergiNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kritikMesajUyari {
            get {
                return ((bool)(this["kritikMesajUyari"]));
            }
            set {
                this["kritikMesajUyari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stokYetersizUyari {
            get {
                return ((bool)(this["stokYetersizUyari"]));
            }
            set {
                this["stokYetersizUyari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kritikRenkUyari {
            get {
                return ((bool)(this["kritikRenkUyari"]));
            }
            set {
                this["kritikRenkUyari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urunBulunamadiUyari {
            get {
                return ((bool)(this["urunBulunamadiUyari"]));
            }
            set {
                this["urunBulunamadiUyari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 1")]
        public string grup1Text {
            get {
                return ((string)(this["grup1Text"]));
            }
            set {
                this["grup1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 2")]
        public string grup2Text {
            get {
                return ((string)(this["grup2Text"]));
            }
            set {
                this["grup2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 3")]
        public string grup3Text {
            get {
                return ((string)(this["grup3Text"]));
            }
            set {
                this["grup3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 4")]
        public string grup4Text {
            get {
                return ((string)(this["grup4Text"]));
            }
            set {
                this["grup4Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 5")]
        public string grup5Text {
            get {
                return ((string)(this["grup5Text"]));
            }
            set {
                this["grup5Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grup 6")]
        public string grup6Text {
            get {
                return ((string)(this["grup6Text"]));
            }
            set {
                this["grup6Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitStok {
            get {
                return ((bool)(this["kilitStok"]));
            }
            set {
                this["kilitStok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitMusteriler {
            get {
                return ((bool)(this["kilitMusteriler"]));
            }
            set {
                this["kilitMusteriler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitCari {
            get {
                return ((bool)(this["kilitCari"]));
            }
            set {
                this["kilitCari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitKasa {
            get {
                return ((bool)(this["kilitKasa"]));
            }
            set {
                this["kilitKasa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitRapor {
            get {
                return ((bool)(this["kilitRapor"]));
            }
            set {
                this["kilitRapor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kilitAyarlar {
            get {
                return ((bool)(this["kilitAyarlar"]));
            }
            set {
                this["kilitAyarlar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urunKisayolManuel {
            get {
                return ((bool)(this["urunKisayolManuel"]));
            }
            set {
                this["urunKisayolManuel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000")]
        public string yonetimSifresi {
            get {
                return ((string)(this["yonetimSifresi"]));
            }
            set {
                this["yonetimSifresi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("En sevdiğin yemek?")]
        public string guvenlikSorusu {
            get {
                return ((string)(this["guvenlikSorusu"]));
            }
            set {
                this["guvenlikSorusu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iskender")]
        public string guvenlikCevabi {
            get {
                return ((string)(this["guvenlikCevabi"]));
            }
            set {
                this["guvenlikCevabi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J20637J005977")]
        public string hddSerial {
            get {
                return ((string)(this["hddSerial"]));
            }
            set {
                this["hddSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string teraziCOM {
            get {
                return ((string)(this["teraziCOM"]));
            }
            set {
                this["teraziCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string teraziAktarimMod {
            get {
                return ((string)(this["teraziAktarimMod"]));
            }
            set {
                this["teraziAktarimMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string teraziStokKodu {
            get {
                return ((string)(this["teraziStokKodu"]));
            }
            set {
                this["teraziStokKodu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string teraziMinDeger {
            get {
                return ((string)(this["teraziMinDeger"]));
            }
            set {
                this["teraziMinDeger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string ekranCOM {
            get {
                return ((string)(this["ekranCOM"]));
            }
            set {
                this["ekranCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2400")]
        public string ekranBaud {
            get {
                return ((string)(this["ekranBaud"]));
            }
            set {
                this["ekranBaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58")]
        public string yaziciBoyut {
            get {
                return ((string)(this["yaziciBoyut"]));
            }
            set {
                this["yaziciBoyut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS58-1")]
        public string yaziciAdi {
            get {
                return ((string)(this["yaziciAdi"]));
            }
            set {
                this["yaziciAdi"] = value;
            }
        }
    }
}
